name: ray_marching
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  # - nvidia::cudatoolkit=11.7
  - python=3.12.8
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  # - opencv=4.7.0
  - pandas=2.2.3
  - pyautogui=0.9.54
  - pysdl2=0.9.16  # torchwindow
  - pyopengl=3.1  # torchwindow
  - cuda-python=12.6.2  # torchwindow
  - pip
  - pip:
    - triton
    - pysdl2-dll==2.28.2  # torchwindow
    - pynput==1.7.6  # mouse and keyboard events
