name: ray_marching
channels:
  - conda-forge
  - nvidia
  - pytorch-nightly
dependencies:
  - nvidia::cudatoolkit=11.7
  - python=3.10
  - pytorch=2.1
  - pytorch-cuda=11.7
  - opencv=4.7.0
  - pandas=1.5.3
  - pyautogui=0.9.48
